//! Generated by scripts/generate_connector_surface.py; do not edit.

use crate::error::ConnectorFailureCode;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    Source,
    Sink,
    Bidirectional,
    Unavailable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Ordering {
    None,
    PerPipeline,
    PerSubject,
    PerPartition,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Acknowledgment {
    SourcePoll,
    DestinationCommit,
    JetstreamAck,
    BrokerAck,
    Http2xx,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Deduplication {
    None,
    EventIdConstraint,
    StreamDuplicateWindow,
    ProducerSession,
    ReceiverContract,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TlsMode {
    NotApplicable,
    OptionalVerify,
    RequiredVerify,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backpressure {
    BoundedBatch,
    PublishTimeout,
    HttpRetryAfter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shutdown {
    Immediate,
    Flush,
    Drain,
}

#[derive(Debug, Clone, Copy)]
pub struct Capabilities {
    pub max_batch_size: u32,
    pub max_batch_bytes: u64,
    pub max_message_bytes: u64,
    pub ordering: Ordering,
    pub acknowledgment: Acknowledgment,
    pub deduplication: Deduplication,
    pub retryable_errors: &'static [ConnectorFailureCode],
    pub permanent_errors: &'static [ConnectorFailureCode],
    pub tls: TlsMode,
    pub authentication: &'static [&'static str],
    pub backpressure: Backpressure,
    pub shutdown: Shutdown,
}

#[derive(Debug, Clone, Copy)]
pub struct ConnectorDescriptor {
    pub id: &'static str,
    pub direction: Direction,
    pub source_types: &'static [&'static str],
    pub sink_types: &'static [&'static str],
    pub cargo_feature: Option<&'static str>,
    pub maturity: &'static str,
    pub config_fields: &'static [&'static str],
    pub capabilities: Option<Capabilities>,
}

pub const CONNECTORS: &[ConnectorDescriptor] = &[
    ConnectorDescriptor {
        id: "postgresql-outbox",
        direction: Direction::Source,
        source_types: &["outbox"],
        sink_types: &[],
        cargo_feature: None,
        maturity: "supported",
        config_fields: &[
            "outbox",
            "subject_template",
            "consumer_group",
            "consumer_id",
            "visibility_seconds",
        ],
        capabilities: Some(Capabilities {
            max_batch_size: 1000,
            max_batch_bytes: 16777216,
            max_message_bytes: 1048576,
            ordering: Ordering::PerPipeline,
            acknowledgment: Acknowledgment::SourcePoll,
            deduplication: Deduplication::None,
            retryable_errors: &[
                ConnectorFailureCode::Unavailable,
                ConnectorFailureCode::Timeout,
                ConnectorFailureCode::Unknown,
            ],
            permanent_errors: &[
                ConnectorFailureCode::ProtocolRejection,
                ConnectorFailureCode::InvalidConfig,
                ConnectorFailureCode::Shutdown,
            ],
            tls: TlsMode::NotApplicable,
            authentication: &["postgres-role"],
            backpressure: Backpressure::BoundedBatch,
            shutdown: Shutdown::Drain,
        }),
    },
    ConnectorDescriptor {
        id: "diagnostics",
        direction: Direction::Sink,
        source_types: &[],
        sink_types: &["stdout", "file"],
        cargo_feature: Some("stdout"),
        maturity: "supported",
        config_fields: &[],
        capabilities: None,
    },
    ConnectorDescriptor {
        id: "postgresql-inbox",
        direction: Direction::Sink,
        source_types: &[],
        sink_types: &["inbox", "pg_outbox"],
        cargo_feature: None,
        maturity: "supported",
        config_fields: &["inbox", "postgres_url"],
        capabilities: Some(Capabilities {
            max_batch_size: 1000,
            max_batch_bytes: 16777216,
            max_message_bytes: 1048576,
            ordering: Ordering::PerPipeline,
            acknowledgment: Acknowledgment::DestinationCommit,
            deduplication: Deduplication::EventIdConstraint,
            retryable_errors: &[
                ConnectorFailureCode::Unavailable,
                ConnectorFailureCode::Timeout,
                ConnectorFailureCode::Unknown,
            ],
            permanent_errors: &[
                ConnectorFailureCode::Authentication,
                ConnectorFailureCode::Authorization,
                ConnectorFailureCode::ProtocolRejection,
                ConnectorFailureCode::MessageTooLarge,
                ConnectorFailureCode::InvalidConfig,
                ConnectorFailureCode::Shutdown,
            ],
            tls: TlsMode::RequiredVerify,
            authentication: &["password", "certificate"],
            backpressure: Backpressure::BoundedBatch,
            shutdown: Shutdown::Drain,
        }),
    },
    ConnectorDescriptor {
        id: "nats-jetstream-sink",
        direction: Direction::Sink,
        source_types: &[],
        sink_types: &["nats"],
        cargo_feature: Some("nats"),
        maturity: "supported",
        config_fields: &["url", "subject", "subject_template"],
        capabilities: Some(Capabilities {
            max_batch_size: 100,
            max_batch_bytes: 16777216,
            max_message_bytes: 1048576,
            ordering: Ordering::PerSubject,
            acknowledgment: Acknowledgment::JetstreamAck,
            deduplication: Deduplication::StreamDuplicateWindow,
            retryable_errors: &[
                ConnectorFailureCode::Unavailable,
                ConnectorFailureCode::Timeout,
                ConnectorFailureCode::Throttled,
                ConnectorFailureCode::Unknown,
            ],
            permanent_errors: &[
                ConnectorFailureCode::Authentication,
                ConnectorFailureCode::Authorization,
                ConnectorFailureCode::TlsVerification,
                ConnectorFailureCode::InvalidDestination,
                ConnectorFailureCode::MessageTooLarge,
                ConnectorFailureCode::ProtocolRejection,
                ConnectorFailureCode::InvalidConfig,
                ConnectorFailureCode::Shutdown,
            ],
            tls: TlsMode::OptionalVerify,
            authentication: &["token", "user_password", "nkey"],
            backpressure: Backpressure::PublishTimeout,
            shutdown: Shutdown::Drain,
        }),
    },
    ConnectorDescriptor {
        id: "webhook-sink",
        direction: Direction::Sink,
        source_types: &[],
        sink_types: &["webhook"],
        cargo_feature: Some("webhook"),
        maturity: "supported",
        config_fields: &[
            "url",
            "timeout_secs",
            "allow_http",
            "ssrf_protection",
            "signing_secret",
            "signing_algorithm",
        ],
        capabilities: Some(Capabilities {
            max_batch_size: 100,
            max_batch_bytes: 16777216,
            max_message_bytes: 1048576,
            ordering: Ordering::PerPipeline,
            acknowledgment: Acknowledgment::Http2xx,
            deduplication: Deduplication::ReceiverContract,
            retryable_errors: &[
                ConnectorFailureCode::Unavailable,
                ConnectorFailureCode::Timeout,
                ConnectorFailureCode::Throttled,
                ConnectorFailureCode::Unknown,
            ],
            permanent_errors: &[
                ConnectorFailureCode::Authentication,
                ConnectorFailureCode::Authorization,
                ConnectorFailureCode::ProtocolRejection,
                ConnectorFailureCode::InvalidDestination,
                ConnectorFailureCode::TlsVerification,
                ConnectorFailureCode::MessageTooLarge,
                ConnectorFailureCode::InvalidConfig,
                ConnectorFailureCode::Shutdown,
            ],
            tls: TlsMode::RequiredVerify,
            authentication: &["hmac_sha256"],
            backpressure: Backpressure::HttpRetryAfter,
            shutdown: Shutdown::Drain,
        }),
    },
    ConnectorDescriptor {
        id: "kafka-sink",
        direction: Direction::Sink,
        source_types: &[],
        sink_types: &["kafka"],
        cargo_feature: Some("kafka"),
        maturity: "supported",
        config_fields: &["brokers", "topic", "topic_template"],
        capabilities: Some(Capabilities {
            max_batch_size: 100,
            max_batch_bytes: 16777216,
            max_message_bytes: 1048576,
            ordering: Ordering::PerPartition,
            acknowledgment: Acknowledgment::BrokerAck,
            deduplication: Deduplication::ProducerSession,
            retryable_errors: &[
                ConnectorFailureCode::Unavailable,
                ConnectorFailureCode::Timeout,
                ConnectorFailureCode::Throttled,
                ConnectorFailureCode::Unknown,
            ],
            permanent_errors: &[
                ConnectorFailureCode::Authentication,
                ConnectorFailureCode::Authorization,
                ConnectorFailureCode::InvalidDestination,
                ConnectorFailureCode::MessageTooLarge,
                ConnectorFailureCode::ProtocolRejection,
                ConnectorFailureCode::InvalidConfig,
                ConnectorFailureCode::Shutdown,
            ],
            tls: TlsMode::RequiredVerify,
            authentication: &["sasl_plain", "sasl_scram", "mtls"],
            backpressure: Backpressure::PublishTimeout,
            shutdown: Shutdown::Flush,
        }),
    },
];

pub const RUNTIME_TYPES: &[&str] = &[
    "file",
    "inbox",
    "kafka",
    "nats",
    "outbox",
    "pg_outbox",
    "stdout",
    "webhook",
];

pub const V1_SUPPORTED_SOURCE_TYPES: &[&str] = &["outbox"];
pub const V1_SUPPORTED_SINK_TYPES: &[&str] = &[
    "file",
    "inbox",
    "kafka",
    "nats",
    "pg_outbox",
    "stdout",
    "webhook",
];

pub fn sink_type_to_descriptor(sink_type: &str) -> Option<&'static ConnectorDescriptor> {
    CONNECTORS
        .iter()
        .find(|descriptor| descriptor.sink_types.contains(&sink_type))
}

pub fn source_type_to_descriptor(source_type: &str) -> Option<&'static ConnectorDescriptor> {
    CONNECTORS
        .iter()
        .find(|descriptor| descriptor.source_types.contains(&source_type))
}

pub fn is_supported_sink_type(sink_type: &str) -> bool {
    V1_SUPPORTED_SINK_TYPES.contains(&sink_type)
}

pub fn is_available(descriptor: &ConnectorDescriptor) -> bool {
    match descriptor.cargo_feature {
        None => true,
        Some("kafka") => cfg!(feature = "kafka"),
        Some("nats") => cfg!(feature = "nats"),
        Some("stdout") => cfg!(feature = "stdout"),
        Some("webhook") => cfg!(feature = "webhook"),
        Some(_) => false,
    }
}
