[package]
name = "pg-tide-ext"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "pg_tide PostgreSQL extension — transactional outbox, idempotent inbox, relay catalog"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg18"]
pg18 = ["pgrx/pg18"]
pg_test = []

[dependencies]
pgrx = { version = "=0.18.0", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
pgrx-tests = "=0.18.0"

[package.metadata.pgrx]
pg_sys_stub = false
