#!/usr/bin/env python3
"""Generate and check the v1 operator-error catalog."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "operator-errors.toml"
RUST = ROOT / "pg-tide-relay/src/operator_errors.rs"
SCHEMA = ROOT / "schemas/operator-errors-v1.json"
DOC = ROOT / "docs/src/reference/error-catalog.md"
RUNBOOKS = ROOT / "docs/runbook-evidence.toml"
START = "<!-- BEGIN GENERATED OPERATOR ERRORS -->"
END = "<!-- END GENERATED OPERATOR ERRORS -->"
REQUIRED = {
    "code", "surface", "component", "summary", "likely_cause", "next_action",
    "runbook", "retryable", "cli_exit_code", "safe_context_keys", "since",
}
CODE_RE = re.compile(r"^(?:operator\.failure|PGTIDE_[A-Z0-9_]{3,48})$")
CONTEXT_RE = re.compile(r"^[a-z][a-z0-9_]{0,31}$")


def fail(message: str) -> None:
    raise ValueError(message)


def load() -> list[dict]:
    try:
        data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        fail(f"cannot read {SOURCE}: {exc}")
    if data.get("schema_version") != 1:
        fail("operator-errors.toml: schema_version must be 1")
    rows = data.get("error")
    if not isinstance(rows, list) or not rows:
        fail("operator-errors.toml: at least one [[error]] row is required")
    runbook_ids = {
        row["id"] for row in tomllib.loads(RUNBOOKS.read_text(encoding="utf-8")).get("runbook", [])
    }
    seen: set[str] = set()
    for row in rows:
        missing = REQUIRED - row.keys()
        if missing:
            fail(f"{row.get('code', '<unknown>')}: missing {sorted(missing)}")
        code = row["code"]
        if not isinstance(code, str) or not CODE_RE.fullmatch(code):
            fail(f"invalid operator code: {code!r}")
        if code in seen:
            fail(f"duplicate operator code: {code}")
        seen.add(code)
        if row["surface"] not in {"cli", "sql", "connector"}:
            fail(f"{code}: invalid surface")
        if not isinstance(row["retryable"], bool):
            fail(f"{code}: retryable must be boolean")
        exit_code = row["cli_exit_code"]
        if exit_code == "null":
            row["cli_exit_code"] = None
            exit_code = None
        if exit_code not in {None, 1, 2}:
            fail(f"{code}: cli_exit_code must be null, 1, or 2")
        if row["surface"] == "sql" and exit_code is not None:
            fail(f"{code}: SQL errors must not have a CLI exit code")
        if row["runbook"] not in runbook_ids:
            fail(f"{code}: unknown runbook {row['runbook']}")
        if not isinstance(row["safe_context_keys"], list) or not all(
            isinstance(key, str) and CONTEXT_RE.fullmatch(key) for key in row["safe_context_keys"]
        ):
            fail(f"{code}: invalid safe_context_keys")
    if "operator.failure" not in seen:
        fail("operator.failure is required")
    return rows


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_rust(rows: list[dict]) -> str:
    lines = [
        "//! Generated by scripts/generate_operator_errors.py; do not edit.",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Descriptor {",
        "    pub code: &'static str,",
        "    pub surface: &'static str,",
        "    pub component: &'static str,",
        "    pub summary: &'static str,",
        "    pub likely_cause: &'static str,",
        "    pub next_action: &'static str,",
        "    pub runbook: &'static str,",
        "    pub retryable: bool,",
        "    pub cli_exit_code: Option<u8>,",
        "    pub safe_context_keys: &'static [&'static str],",
        "    pub since: &'static str,",
        "}",
        "",
        "pub const DESCRIPTORS: &[Descriptor] = &[",
    ]
    for row in rows:
        contexts = ", ".join(rust_string(key) for key in row["safe_context_keys"])
        exit_code = "None" if row["cli_exit_code"] is None else f"Some({row['cli_exit_code']})"
        lines.extend([
            "    Descriptor {",
            f"        code: {rust_string(row['code'])},",
            f"        surface: {rust_string(row['surface'])},",
            f"        component: {rust_string(row['component'])},",
            f"        summary: {rust_string(row['summary'])},",
            f"        likely_cause: {rust_string(row['likely_cause'])},",
            f"        next_action: {rust_string(row['next_action'])},",
            f"        runbook: {rust_string(row['runbook'])},",
            f"        retryable: {str(row['retryable']).lower()},",
            f"        cli_exit_code: {exit_code},",
            f"        safe_context_keys: &[{contexts}],",
            f"        since: {rust_string(row['since'])},",
            "    },",
        ])
    lines.extend([
        "];",
        "",
        "pub fn find(code: &str) -> Option<&'static Descriptor> {",
        "    DESCRIPTORS.iter().find(|descriptor| descriptor.code == code)",
        "}",
        "",
    ])
    source = "\n".join(lines)
    result = subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input=source,
        capture_output=True,
        check=True,
        text=True,
    )
    return result.stdout


def render_schema(rows: list[dict]) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://pg-tide.dev/schemas/operator-errors-v1.json",
        "title": "pg-tide operator error catalog",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "errors"],
        "properties": {
            "schema_version": {"const": 1},
            "errors": {
                "type": "array",
                "items": {"$ref": "#/$defs/error"},
                "minItems": 1,
                "uniqueItems": True,
            },
        },
        "$defs": {
            "error": {
                "type": "object",
                "additionalProperties": False,
                "required": sorted(REQUIRED),
                "properties": {
                    "code": {"type": "string", "pattern": CODE_RE.pattern},
                    "surface": {"enum": ["cli", "sql", "connector"]},
                    "component": {"type": "string"},
                    "summary": {"type": "string"},
                    "likely_cause": {"type": "string"},
                    "next_action": {"type": "string"},
                    "runbook": {"type": "string"},
                    "retryable": {"type": "boolean"},
                    "cli_exit_code": {"type": ["integer", "null"], "enum": [1, 2, None]},
                    "safe_context_keys": {"type": "array", "items": {"type": "string"}},
                    "since": {"type": "string"},
                },
            }
        },
    }
    return json.dumps({"schema_version": 1, "errors": rows}, indent=2, ensure_ascii=False) + "\n"


def render_doc(rows: list[dict]) -> str:
    lines = [
        "# Operator error catalog",
        "",
        "The relay emits the five frozen CLI diagnostic fields. Retryability,",
        "runbook ownership, safe context, and exit metadata are defined here.",
        "",
        START,
        "| Code | Surface | Summary | Retryable | Exit | Runbook |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]
    for row in rows:
        exit_code = "—" if row["cli_exit_code"] is None else str(row["cli_exit_code"])
        lines.append(
            f"| `{row['code']}` | {row['surface']} | {row['summary']} | "
            f"{str(row['retryable']).lower()} | {exit_code} | `{row['runbook']}` |"
        )
    lines.extend([END, ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rows = load()
        outputs = {RUST: render_rust(rows), SCHEMA: render_schema(rows), DOC: render_doc(rows)}
        for path, content in outputs.items():
            if args.check:
                if path.read_text(encoding="utf-8") != content:
                    fail(f"generated output is stale: {path}")
            else:
                path.write_text(content, encoding="utf-8")
    except (OSError, ValueError) as exc:
        print(f"operator-error catalog: {exc}", file=sys.stderr)
        return 1
    print("operator-error catalog: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
