-- pg_tide 0.14.0 → 0.15.0
--
-- v0.15.0: TLS Enforcement, Secret Redaction, Outbox Retention Sweep,
--          Worker Resilience, Connection Pooling, Schema Registry Passthrough.
--
-- Changes:
--   1. Outbox Retention Sweep: tide.outbox_truncate_delivered() function that
--      deletes consumed messages older than the configured retention_hours.
--
-- v0.17.0 note: tide.outbox_truncate_delivered() is implemented as a Rust
-- #[pg_extern] in pg-tide-ext/src/outbox.rs and is the single source of truth.
-- The plpgsql definition that was previously here has been removed to eliminate
-- the duplicate-definition hazard identified in overall_assessment_3 §1.2.
-- The 0.16.0→0.17.0 migration drops any plpgsql version left on upgraded
-- installations.
