-- pg_tide 0.15.0 → 0.16.0
--
-- v0.16.0: Developer Experience & Observability
--
-- Changes:
--   1. outbox_create_if_not_exists() — idempotent outbox creation helper.
--   2. relay_set_inbox_v2() — single-JSONB parameter version with documented keys.
--      The original 8-parameter relay_set_inbox() signature is retained as a
--      compatibility shim.
--   3. Documentation comments on relay_enable() / relay_disable() clarifying the
--      intentional silent no-op when the pipeline does not exist.

-- ── 1. outbox_create_if_not_exists() ────────────────────────────────────────
--
-- v0.17.0 note: tide.outbox_create_if_not_exists() is implemented as a Rust
-- #[pg_extern] in pg-tide-ext/src/outbox.rs and is the single source of truth.
-- The plpgsql definition that was previously here has been removed to eliminate
-- the duplicate-definition hazard (overall_assessment_3 §1.2).
-- The 0.16.0→0.17.0 migration drops any plpgsql version left on upgraded
-- installations.

-- ── 2. relay_set_inbox_v2() — single-JSONB config parameter ─────────────────
--
-- v0.17.0 note: tide.relay_set_inbox_v2() is implemented as a Rust #[pg_extern]
-- in pg-tide-ext/src/relay.rs and is the single source of truth.
-- The plpgsql definition that was previously here has been removed to eliminate
-- the duplicate-definition hazard (overall_assessment_3 §1.2).
-- The 0.16.0→0.17.0 migration drops any plpgsql version left on upgraded
-- installations.

-- ── 3. Documentation note on relay_enable / relay_disable behaviour ──────────
--
-- relay_enable(TEXT) and relay_disable(TEXT) are pgrx-defined functions whose
-- doc comments are maintained in Rust source (pg-tide-ext/src/relay.rs).
-- Behaviour note: both functions are intentional silent no-ops when the named
-- pipeline does not exist — callers are not required to verify existence first.
