-- pg_tide 0.1.0 → 0.2.0 upgrade script
--
-- To upgrade: ALTER EXTENSION pg_tide UPDATE TO '0.2.0';
--
-- 0.2.0 is a hardening release with no schema changes.
-- The compiled extension artefact is updated; no DDL migrations are required.
